-- ============================================================================
-- PassGo — seed data (50 countries + Kenyan (KE) passport visa rules)
-- Run AFTER schema.sql. Idempotent via ON CONFLICT.
-- Image URLs use picsum.photos placeholders — replace with real assets later.
-- Visa data is INDICATIVE for demo purposes; the official_link is authoritative.
-- ============================================================================

-- ── COUNTRIES (1–24: full detail, mirror src/data/mockCountries.ts) ──────────
insert into countries (id, code, name, flag, region, capital, currency, currency_name, languages, daily_budget_usd, budget_tier, suggested_days, best_season, hero_image, summary, popularity_rank) values
('c_tz','TZ','Tanzania','🇹🇿','Africa','Dodoma','TZS','Tanzanian Shilling',ARRAY['Swahili','English'],55,'budget',7,'Jun–Oct (dry / safari)','https://picsum.photos/seed/passgo-tz-hero/1200/800','Zanzibar spice islands, the Serengeti migration and Kilimanjaro.',1),
('c_za','ZA','South Africa','🇿🇦','Africa','Pretoria','ZAR','South African Rand',ARRAY['English','Zulu','Afrikaans'],80,'moderate',8,'Oct–Apr (summer)','https://picsum.photos/seed/passgo-za-hero/1200/800','Table Mountain, the Garden Route and Big Five safaris.',2),
('c_rw','RW','Rwanda','🇷🇼','Africa','Kigali','RWF','Rwandan Franc',ARRAY['Kinyarwanda','English','French'],60,'moderate',5,'Jun–Sep (dry)','https://picsum.photos/seed/passgo-rw-hero/1200/800','Mountain gorilla trekking, spotless Kigali and Lake Kivu.',9),
('c_ug','UG','Uganda','🇺🇬','Africa','Kampala','UGX','Ugandan Shilling',ARRAY['English','Swahili','Luganda'],45,'budget',6,'Dec–Feb, Jun–Aug','https://picsum.photos/seed/passgo-ug-hero/1200/800','The source of the Nile, rafting at Jinja and Bwindi gorillas.',14),
('c_mu','MU','Mauritius','🇲🇺','Africa','Port Louis','MUR','Mauritian Rupee',ARRAY['English','French','Creole'],110,'luxury',6,'May–Dec (dry)','https://picsum.photos/seed/passgo-mu-hero/1200/800','Turquoise lagoons, luxury resorts and the underwater waterfall illusion.',6),
('c_sc','SC','Seychelles','🇸🇨','Africa','Victoria','SCR','Seychellois Rupee',ARRAY['Creole','English','French'],140,'luxury',6,'Apr–May, Oct–Nov','https://picsum.photos/seed/passgo-sc-hero/1200/800','Granite-fringed beaches and giant tortoises.',12),
('c_zw','ZW','Zimbabwe','🇿🇼','Africa','Harare','USD','US Dollar',ARRAY['English','Shona','Ndebele'],70,'moderate',5,'Aug–Oct','https://picsum.photos/seed/passgo-zw-hero/1200/800','Victoria Falls, Hwange elephants and Mana Pools.',16),
('c_et','ET','Ethiopia','🇪🇹','Africa','Addis Ababa','ETB','Ethiopian Birr',ARRAY['Amharic','Oromo'],50,'budget',7,'Oct–Mar','https://picsum.photos/seed/passgo-et-hero/1200/800','Rock-hewn churches of Lalibela and the Simien Mountains.',18),
('c_eg','EG','Egypt','🇪🇬','Africa','Cairo','EGP','Egyptian Pound',ARRAY['Arabic'],55,'budget',8,'Oct–Apr','https://picsum.photos/seed/passgo-eg-hero/1200/800','Pyramids of Giza, Nile cruises and the temples of Luxor.',7),
('c_ma','MA','Morocco','🇲🇦','Africa','Rabat','MAD','Moroccan Dirham',ARRAY['Arabic','Berber','French'],60,'moderate',8,'Mar–May, Sep–Nov','https://picsum.photos/seed/passgo-ma-hero/1200/800','Marrakech souks, blue Chefchaouen and nights in the Sahara.',11),
('c_th','TH','Thailand','🇹🇭','Asia','Bangkok','THB','Thai Baht',ARRAY['Thai'],45,'budget',10,'Nov–Mar (cool/dry)','https://picsum.photos/seed/passgo-th-hero/1200/800','Street-food capital, glittering temples and Andaman islands.',3),
('c_sg','SG','Singapore','🇸🇬','Asia','Singapore','SGD','Singapore Dollar',ARRAY['English','Malay','Mandarin','Tamil'],120,'luxury',4,'Feb–Apr','https://picsum.photos/seed/passgo-sg-hero/1200/800','A futuristic garden city of hawker centres and Marina Bay.',5),
('c_my','MY','Malaysia','🇲🇾','Asia','Kuala Lumpur','MYR','Malaysian Ringgit',ARRAY['Malay','English'],50,'budget',7,'Mar–Oct','https://picsum.photos/seed/passgo-my-hero/1200/800','Petronas Towers, Borneo rainforests and Penang food.',13),
('c_id','ID','Indonesia','🇮🇩','Asia','Jakarta','IDR','Indonesian Rupiah',ARRAY['Indonesian'],45,'budget',9,'Apr–Oct (dry)','https://picsum.photos/seed/passgo-id-hero/1200/800','Bali rice terraces, Komodo dragons and 17,000 islands.',4),
('c_lk','LK','Sri Lanka','🇱🇰','Asia','Colombo','LKR','Sri Lankan Rupee',ARRAY['Sinhala','Tamil'],40,'budget',9,'Dec–Mar (west/south)','https://picsum.photos/seed/passgo-lk-hero/1200/800','Tea-country trains, ancient Sigiriya and southern surf.',15),
('c_mv','MV','Maldives','🇲🇻','Asia','Malé','MVR','Maldivian Rufiyaa',ARRAY['Dhivehi','English'],200,'luxury',5,'Nov–Apr (dry)','https://picsum.photos/seed/passgo-mv-hero/1200/800','Overwater villas, house reefs and a free visa on arrival.',10),
('c_hk','HK','Hong Kong','🇭🇰','Asia','Hong Kong','HKD','Hong Kong Dollar',ARRAY['Cantonese','English'],110,'luxury',4,'Oct–Dec','https://picsum.photos/seed/passgo-hk-hero/1200/800','Victoria Peak skyline, dim sum and the Star Ferry.',17),
('c_ae','AE','United Arab Emirates','🇦🇪','Middle East','Abu Dhabi','AED','UAE Dirham',ARRAY['Arabic','English'],130,'luxury',5,'Nov–Mar','https://picsum.photos/seed/passgo-ae-hero/1200/800','Dubai skyline, desert safaris and Abu Dhabi grand mosque.',8),
('c_qa','QA','Qatar','🇶🇦','Middle East','Doha','QAR','Qatari Riyal',ARRAY['Arabic','English'],120,'luxury',3,'Nov–Mar','https://picsum.photos/seed/passgo-qa-hero/1200/800','Doha Museum of Islamic Art and the Souq Waqif.',19),
('c_tr','TR','Türkiye','🇹🇷','Europe','Ankara','TRY','Turkish Lira',ARRAY['Turkish'],60,'moderate',8,'Apr–Jun, Sep–Nov','https://picsum.photos/seed/passgo-tr-hero/1200/800','Istanbul two continents, Cappadocia balloons and Pamukkale.',7),
('c_mz','MZ','Mozambique','🇲🇿','Africa','Maputo','MZN','Mozambican Metical',ARRAY['Portuguese'],65,'moderate',6,'May–Nov (dry)','https://picsum.photos/seed/passgo-mz-hero/1200/800','Bazaruto archipelago, peri-peri seafood and ocean beaches.',21),
('c_jm','JM','Jamaica','🇯🇲','Caribbean','Kingston','JMD','Jamaican Dollar',ARRAY['English','Patois'],95,'moderate',6,'Nov–Apr','https://picsum.photos/seed/passgo-jm-hero/1200/800','Reggae birthplace — Dunn''s River Falls and Negril sunsets.',22),
('c_bb','BB','Barbados','🇧🇧','Caribbean','Bridgetown','BBD','Barbadian Dollar',ARRAY['English'],120,'luxury',6,'Dec–Apr','https://picsum.photos/seed/passgo-bb-hero/1200/800','Platinum-coast beaches, rum distilleries and turtle swims.',23),
('c_fj','FJ','Fiji','🇫🇯','Oceania','Suva','FJD','Fijian Dollar',ARRAY['English','Fijian','Hindi'],120,'luxury',7,'May–Oct (dry)','https://picsum.photos/seed/passgo-fj-hero/1200/800','333 islands of soft-coral diving and warm hospitality.',24)
on conflict (id) do nothing;

-- ── COUNTRIES (25–50: compact, to reach 50 popular destinations) ─────────────
insert into countries (id, code, name, flag, region, capital, currency, currency_name, languages, daily_budget_usd, budget_tier, suggested_days, best_season, popularity_rank) values
('c_na','NA','Namibia','🇳🇦','Africa','Windhoek','NAD','Namibian Dollar',ARRAY['English'],75,'moderate',8,'May–Oct',25),
('c_bw','BW','Botswana','🇧🇼','Africa','Gaborone','BWP','Botswana Pula',ARRAY['English','Setswana'],120,'luxury',6,'May–Sep',26),
('c_zm','ZM','Zambia','🇿🇲','Africa','Lusaka','ZMW','Zambian Kwacha',ARRAY['English'],70,'moderate',5,'May–Oct',27),
('c_mw','MW','Malawi','🇲🇼','Africa','Lilongwe','MWK','Malawian Kwacha',ARRAY['English','Chichewa'],45,'budget',6,'May–Oct',28),
('c_sn','SN','Senegal','🇸🇳','Africa','Dakar','XOF','West African CFA',ARRAY['French','Wolof'],60,'moderate',6,'Nov–Feb',29),
('c_gh','GH','Ghana','🇬🇭','Africa','Accra','GHS','Ghanaian Cedi',ARRAY['English'],55,'budget',7,'Nov–Mar',30),
('c_ci','CI','Côte d''Ivoire','🇨🇮','Africa','Yamoussoukro','XOF','West African CFA',ARRAY['French'],65,'moderate',6,'Nov–Mar',31),
('c_ng','NG','Nigeria','🇳🇬','Africa','Abuja','NGN','Nigerian Naira',ARRAY['English'],70,'moderate',6,'Nov–Mar',32),
('c_cv','CV','Cape Verde','🇨🇻','Africa','Praia','CVE','Cape Verdean Escudo',ARRAY['Portuguese'],85,'moderate',6,'Nov–Jun',33),
('c_mg','MG','Madagascar','🇲🇬','Africa','Antananarivo','MGA','Malagasy Ariary',ARRAY['Malagasy','French'],50,'budget',9,'Apr–Oct',34),
('c_km','KM','Comoros','🇰🇲','Africa','Moroni','KMF','Comorian Franc',ARRAY['Comorian','French','Arabic'],55,'budget',5,'May–Oct',35),
('c_ph','PH','Philippines','🇵🇭','Asia','Manila','PHP','Philippine Peso',ARRAY['Filipino','English'],45,'budget',10,'Dec–Apr',36),
('c_kr','KR','South Korea','🇰🇷','Asia','Seoul','KRW','South Korean Won',ARRAY['Korean'],100,'luxury',6,'Mar–May, Sep–Nov',37),
('c_jp','JP','Japan','🇯🇵','Asia','Tokyo','JPY','Japanese Yen',ARRAY['Japanese'],120,'luxury',10,'Mar–Apr, Oct–Nov',38),
('c_cn','CN','China','🇨🇳','Asia','Beijing','CNY','Chinese Yuan',ARRAY['Mandarin'],70,'moderate',10,'Apr–May, Sep–Oct',39),
('c_np','NP','Nepal','🇳🇵','Asia','Kathmandu','NPR','Nepalese Rupee',ARRAY['Nepali'],35,'budget',12,'Oct–Nov, Mar–Apr',40),
('c_kh','KH','Cambodia','🇰🇭','Asia','Phnom Penh','KHR','Cambodian Riel',ARRAY['Khmer'],40,'budget',7,'Nov–Feb',41),
('c_vn','VN','Vietnam','🇻🇳','Asia','Hanoi','VND','Vietnamese Dong',ARRAY['Vietnamese'],40,'budget',12,'Feb–Apr',42),
('c_jo','JO','Jordan','🇯🇴','Middle East','Amman','JOD','Jordanian Dinar',ARRAY['Arabic'],85,'moderate',6,'Mar–May, Sep–Nov',43),
('c_om','OM','Oman','🇴🇲','Middle East','Muscat','OMR','Omani Rial',ARRAY['Arabic'],110,'luxury',6,'Oct–Mar',44),
('c_bh','BH','Bahrain','🇧🇭','Middle East','Manama','BHD','Bahraini Dinar',ARRAY['Arabic'],100,'luxury',3,'Nov–Mar',45),
('c_br','BR','Brazil','🇧🇷','South America','Brasília','BRL','Brazilian Real',ARRAY['Portuguese'],75,'moderate',10,'Dec–Mar',46),
('c_ar','AR','Argentina','🇦🇷','South America','Buenos Aires','ARS','Argentine Peso',ARRAY['Spanish'],70,'moderate',10,'Nov–Mar',47),
('c_pa','PA','Panama','🇵🇦','North America','Panama City','PAB','Panamanian Balboa',ARRAY['Spanish'],80,'moderate',6,'Dec–Apr',48),
('c_dm','DM','Dominica','🇩🇲','Caribbean','Roseau','XCD','East Caribbean Dollar',ARRAY['English'],90,'moderate',6,'Feb–Jun',49),
('c_vu','VU','Vanuatu','🇻🇺','Oceania','Port Vila','VUV','Vanuatu Vatu',ARRAY['Bislama','English','French'],110,'luxury',7,'May–Oct',50)
on conflict (id) do nothing;

-- ── VISA RULES for the KENYAN (KE) passport — all 50 destinations ────────────
insert into visa_rules (id, passport_country, dest_country, visa_type, cost_usd, processing_days, stay_days, official_link, notes) values
('v_ke_tz','KE','TZ','visa_free',0,0,90,'https://visa.immigration.go.tz/','EAC — enter on a valid passport or EAC ID.'),
('v_ke_za','KE','ZA','visa_free',0,0,90,'https://www.dha.gov.za/','Visa exemption for tourism up to 90 days.'),
('v_ke_rw','KE','RW','visa_free',0,0,180,'https://www.migration.gov.rw/','EAC citizens enter visa-free.'),
('v_ke_ug','KE','UG','visa_free',0,0,180,'https://visas.immigration.go.ug/','EAC citizens enter visa-free.'),
('v_ke_mu','KE','MU','visa_free',0,0,90,'https://passport.govmu.org/','Proof of accommodation may be requested.'),
('v_ke_sc','KE','SC','visa_free',0,0,90,'https://www.ics.gov.sc/','Free visitor permit on arrival; Travel Authorization online first.'),
('v_ke_zw','KE','ZW','visa_on_arrival',30,0,30,'https://www.evisa.gov.zw/','Single-entry VoA; KAZA UniVisa also covers Zambia.'),
('v_ke_et','KE','ET','evisa',82,3,30,'https://www.evisa.gov.et/','Apply online; e-Visa emailed before departure.'),
('v_ke_eg','KE','EG','evisa',25,7,30,'https://visa2egypt.gov.eg/','Single-entry e-Visa; apply a week ahead.'),
('v_ke_ma','KE','MA','visa_required',27,10,90,'https://www.consulat.ma/','Apply at the Moroccan consulate.'),
('v_ke_th','KE','TH','visa_free',0,0,30,'https://www.thaievisa.go.th/','Visa exemption for tourism.'),
('v_ke_sg','KE','SG','visa_free',0,0,30,'https://www.ica.gov.sg/','Submit the SG Arrival Card before arrival.'),
('v_ke_my','KE','MY','visa_free',0,0,30,'https://malaysiavisa.imi.gov.my/','Complete the MDAC before travel.'),
('v_ke_id','KE','ID','visa_on_arrival',35,0,30,'https://molina.imigrasi.go.id/','e-VoA online; extendable once.'),
('v_ke_lk','KE','LK','eta',50,1,30,'https://www.eta.gov.lk/','Electronic Travel Authorization; double-entry.'),
('v_ke_mv','KE','MV','visa_on_arrival',0,0,30,'https://imuga.immigration.gov.mv/','Free VoA; submit IMUGA declaration first.'),
('v_ke_hk','KE','HK','visa_free',0,0,30,'https://www.immd.gov.hk/','Visa-free entry for tourism.'),
('v_ke_ae','KE','AE','evisa',90,4,30,'https://smartservices.icp.gov.ae/','Tourist e-Visa, often via airline or hotel.'),
('v_ke_qa','KE','QA','visa_free',0,0,30,'https://www.visitqatar.com/','Visa waiver on arrival; passport valid 6+ months.'),
('v_ke_tr','KE','TR','evisa',60,1,30,'https://www.evisa.gov.tr/','Quick online e-Visa; single entry.'),
('v_ke_mz','KE','MZ','visa_on_arrival',50,0,30,'https://evisa.gov.mz/','VoA at main entry points; pre-apply to save time.'),
('v_ke_jm','KE','JM','visa_free',0,0,90,'https://www.pica.gov.jm/','Visa-free; complete the C5 form online.'),
('v_ke_bb','KE','BB','visa_free',0,0,90,'https://www.immigration.gov.bb/','Visa-free for tourism up to 90 days.'),
('v_ke_fj','KE','FJ','visa_free',0,0,120,'https://www.immigration.gov.fj/','Visitor permit granted on arrival.'),
('v_ke_na','KE','NA','visa_free',0,0,90,'https://mha.gov.na/','Visa-free for tourism.'),
('v_ke_bw','KE','BW','visa_free',0,0,90,'https://www.gov.bw/','Visa-free for tourism.'),
('v_ke_zm','KE','ZM','visa_on_arrival',50,0,90,'https://eservices.zambiaimmigration.gov.zm/','VoA / KAZA UniVisa at major entry points.'),
('v_ke_mw','KE','MW','visa_on_arrival',75,0,30,'https://www.evisa.gov.mw/','VoA or e-Visa.'),
('v_ke_sn','KE','SN','visa_free',0,0,90,'https://www.dgpsn.gouv.sn/','Visa-free for tourism.'),
('v_ke_gh','KE','GH','evisa',60,5,30,'https://eservices.gis.gov.gh/','Apply online before travel.'),
('v_ke_ci','KE','CI','evisa',73,3,90,'https://snedai.com/','e-Visa, collect biometrics on arrival.'),
('v_ke_ng','KE','NG','visa_required',160,14,90,'https://portal.immigration.gov.ng/','Apply online and at the embassy.'),
('v_ke_cv','KE','CV','eta',35,1,30,'https://www.ease.gov.cv/','Airport security tax / EASE pre-registration.'),
('v_ke_mg','KE','MG','visa_on_arrival',37,0,30,'https://www.evisamada.gov.mg/','VoA or e-Visa.'),
('v_ke_km','KE','KM','visa_on_arrival',30,0,45,'https://www.gouvernement.km/','VoA at Moroni airport.'),
('v_ke_ph','KE','PH','visa_free',0,0,30,'https://immigration.gov.ph/','Visa-free for tourism up to 30 days.'),
('v_ke_kr','KE','KR','eta',10,3,90,'https://www.k-eta.go.kr/','K-ETA required before boarding.'),
('v_ke_jp','KE','JP','visa_required',0,5,90,'https://www.mofa.go.jp/','Apply at the Japanese embassy.'),
('v_ke_cn','KE','CN','visa_required',60,7,30,'https://bio.visaforchina.cn/','Apply at the Chinese visa centre.'),
('v_ke_np','KE','NP','visa_on_arrival',30,0,30,'https://nepaliport.immigration.gov.np/','VoA at Kathmandu airport.'),
('v_ke_kh','KE','KH','evisa',36,3,30,'https://www.evisa.gov.kh/','e-Visa online; single entry.'),
('v_ke_vn','KE','VN','evisa',25,3,90,'https://evisa.xuatnhapcanh.gov.vn/','e-Visa online; single or multiple entry.'),
('v_ke_jo','KE','JO','visa_on_arrival',56,0,30,'https://international.visitjordan.com/','VoA; free with the Jordan Pass.'),
('v_ke_om','KE','OM','evisa',13,3,10,'https://evisa.rop.gov.om/','e-Visa online.'),
('v_ke_bh','KE','BH','evisa',29,3,14,'https://www.evisa.gov.bh/','e-Visa online.'),
('v_ke_br','KE','BR','visa_required',80,12,90,'https://www.gov.br/mre/','Apply at the Brazilian consulate.'),
('v_ke_ar','KE','AR','visa_required',150,20,90,'https://www.argentina.gob.ar/interior/migraciones','Apply at the Argentine consulate.'),
('v_ke_pa','KE','PA','evisa',50,5,30,'https://www.migracion.gob.pa/','Authorised/stamped visa; may be issued online.'),
('v_ke_dm','KE','DM','visa_free',0,0,180,'https://dominica.gov.dm/','Visa-free for tourism.'),
('v_ke_vu','KE','VU','visa_free',0,0,30,'https://immigration.gov.vu/','Visa-free for tourism up to 30 days.')
on conflict (passport_country, dest_country) do nothing;

-- ── CITIES (flagship destinations) ───────────────────────────────────────────
insert into cities (id, country_code, name, lat, lng, image, blurb, suggested_days) values
('city_zanzibar','TZ','Zanzibar (Stone Town)',-6.1659,39.2026,'https://picsum.photos/seed/passgo-zanzibar/1200/800','UNESCO maze of spice-trade lanes, beaches and dhow sunsets.',3),
('city_arusha','TZ','Arusha',-3.3869,36.6830,'https://picsum.photos/seed/passgo-arusha/1200/800','Safari gateway to the Serengeti and Ngorongoro Crater.',2),
('city_capetown','ZA','Cape Town',-33.9249,18.4241,'https://picsum.photos/seed/passgo-capetown/1200/800','Table Mountain, the Cape Peninsula and the V&A Waterfront.',4),
('city_joburg','ZA','Johannesburg',-26.2041,28.0473,'https://picsum.photos/seed/passgo-joburg/1200/800','History at the Apartheid Museum and a launchpad to Kruger.',2),
('city_bangkok','TH','Bangkok',13.7563,100.5018,'https://picsum.photos/seed/passgo-bangkok/1200/800','Grand palaces, floating markets and legendary street food.',3),
('city_chiangmai','TH','Chiang Mai',18.7883,98.9853,'https://picsum.photos/seed/passgo-chiangmai/1200/800','Mountain temples, night bazaars and elephant sanctuaries.',3),
('city_phuket','TH','Phuket',7.8804,98.3923,'https://picsum.photos/seed/passgo-phuket/1200/800','Andaman beaches and the gateway to Phi Phi.',3),
('city_dubai','AE','Dubai',25.2048,55.2708,'https://picsum.photos/seed/passgo-dubai/1200/800','Burj Khalifa, desert dunes and the world''s largest mall.',3),
('city_abudhabi','AE','Abu Dhabi',24.4539,54.3773,'https://picsum.photos/seed/passgo-abudhabi/1200/800','Sheikh Zayed Grand Mosque and Louvre Abu Dhabi.',2),
('city_istanbul','TR','Istanbul',41.0082,28.9784,'https://picsum.photos/seed/passgo-istanbul/1200/800','Where Europe meets Asia — Hagia Sophia and the Bosphorus.',4),
('city_cappadocia','TR','Cappadocia (Göreme)',38.6431,34.8289,'https://picsum.photos/seed/passgo-cappadocia/1200/800','Fairy chimneys, cave hotels and sunrise balloons.',2),
('city_portlouis','MU','Port Louis',-20.1609,57.5012,'https://picsum.photos/seed/passgo-portlouis/1200/800','Caudan Waterfront, central market and colonial core.',1),
('city_flicenflac','MU','Flic en Flac',-20.2747,57.3661,'https://picsum.photos/seed/passgo-flicenflac/1200/800','West-coast lagoon beaches and Black River Gorges nearby.',3)
on conflict (id) do nothing;

-- ── ATTRACTIONS (subset; mirror src/data/mockAttractions.ts) ─────────────────
insert into attractions (id, city_id, name, category, image, lat, lng, opening_hours, fee_usd, rating, duration_hours, blurb) values
('a_stonetown','city_zanzibar','Stone Town Walking Tour','Heritage','https://picsum.photos/seed/passgo-stonetown/1200/800',-6.1626,39.1885,'Daily, guided 09:00–17:00',15,4.7,3,'Carved doors, the old slave market and Freddie Mercury''s birthplace.'),
('a_nakupenda','city_zanzibar','Nakupenda Sandbank','Beach','https://picsum.photos/seed/passgo-nakupenda/1200/800',-6.1800,39.1600,'Tours depart 09:30',40,4.8,5,'A disappearing white sandbank with a beach seafood lunch.'),
('a_jozani','city_zanzibar','Jozani Forest (Red Colobus)','Nature','https://picsum.photos/seed/passgo-jozani/1200/800',-6.2667,39.4167,'07:30–17:00',10,4.5,2,'Boardwalk through mangroves to see endemic red colobus monkeys.'),
('a_ngorongoro','city_arusha','Ngorongoro Crater Day Safari','Safari','https://picsum.photos/seed/passgo-ngorongoro/1200/800',-3.1667,35.5833,'06:00–18:00',70,4.9,10,'A collapsed caldera teeming with lions, rhino and flamingos.'),
('a_arushanp','city_arusha','Arusha National Park','Nature','https://picsum.photos/seed/passgo-arushanp/1200/800',-3.2500,36.8333,'06:30–18:30',45,4.4,6,'Canoeing, Mt Meru views and giraffes — an easy day from town.'),
('a_tablemountain','city_capetown','Table Mountain Cableway','Viewpoint','https://picsum.photos/seed/passgo-tablemountain/1200/800',-33.9628,18.4098,'08:00–18:00',22,4.8,3,'Rotating cable car to the flat-topped summit.'),
('a_capepoint','city_capetown','Cape of Good Hope','Nature','https://picsum.photos/seed/passgo-capepoint/1200/800',-34.3568,18.4740,'07:00–17:00',21,4.7,5,'Dramatic cliffs at the peninsula''s tip, with penguins en route.'),
('a_robben','city_capetown','Robben Island','Heritage','https://picsum.photos/seed/passgo-robben/1200/800',-33.8067,18.3667,'Ferries 09:00, 11:00, 13:00',33,4.6,4,'Ferry to the prison where Nelson Mandela was held.'),
('a_apartheid','city_joburg','Apartheid Museum','Museum','https://picsum.photos/seed/passgo-apartheid/1200/800',-26.2378,28.0089,'09:00–17:00, closed Mon',9,4.8,3,'A powerful telling of South Africa''s road to democracy.'),
('a_soweto','city_joburg','Soweto & Vilakazi Street','Heritage','https://picsum.photos/seed/passgo-soweto/1200/800',-26.2375,27.9089,'Tours daily',35,4.7,4,'The only street to have housed two Nobel laureates.'),
('a_grandpalace','city_bangkok','Grand Palace & Wat Phra Kaew','Heritage','https://picsum.photos/seed/passgo-grandpalace/1200/800',13.7500,100.4915,'08:30–15:30',14,4.6,3,'Gilded royal complex housing the Emerald Buddha.'),
('a_watarun','city_bangkok','Wat Arun','Temple','https://picsum.photos/seed/passgo-watarun/1200/800',13.7437,100.4889,'08:00–18:00',3,4.7,1.5,'The porcelain Temple of Dawn on the Chao Phraya.'),
('a_chatuchak','city_bangkok','Chatuchak Weekend Market','Market','https://picsum.photos/seed/passgo-chatuchak/1200/800',13.7999,100.5503,'Sat–Sun 09:00–18:00',0,4.5,3,'15,000 stalls of street food, vintage and crafts.'),
('a_doisuthep','city_chiangmai','Wat Phra That Doi Suthep','Temple','https://picsum.photos/seed/passgo-doisuthep/1200/800',18.8048,98.9217,'06:00–20:00',1,4.7,2,'Golden mountain temple with sweeping views.'),
('a_elephant','city_chiangmai','Ethical Elephant Sanctuary','Nature','https://picsum.photos/seed/passgo-elephant/1200/800',19.0500,98.8500,'Half-day 09:00 / 13:00',55,4.9,5,'Feed and walk with rescued elephants — no riding.'),
('a_phiphi','city_phuket','Phi Phi Islands Day Trip','Beach','https://picsum.photos/seed/passgo-phiphi/1200/800',7.7407,98.7784,'Speedboats depart 08:00',45,4.6,8,'Maya Bay, snorkelling lagoons and limestone cliffs.'),
('a_bigbuddha','city_phuket','Big Buddha','Viewpoint','https://picsum.photos/seed/passgo-bigbuddha/1200/800',7.8276,98.3122,'06:00–19:00',0,4.5,1.5,'45m marble Buddha with 360° island views.'),
('a_burjkhalifa','city_dubai','Burj Khalifa — At the Top','Viewpoint','https://picsum.photos/seed/passgo-burjkhalifa/1200/800',25.1972,55.2744,'08:30–22:00',41,4.7,2,'Observation decks on the world''s tallest building.'),
('a_desertsafari','city_dubai','Desert Safari & BBQ','Adventure','https://picsum.photos/seed/passgo-desertsafari/1200/800',24.9000,55.5000,'Pickups from 15:00',65,4.8,6,'Dune bashing, camels, sandboarding and a desert dinner.'),
('a_dubaimall','city_dubai','Dubai Mall & Fountain','Shopping','https://picsum.photos/seed/passgo-dubaimall/1200/800',25.1985,55.2796,'10:00–24:00',0,4.6,3,'Aquarium, ice rink and the choreographed fountain.'),
('a_grandmosque','city_abudhabi','Sheikh Zayed Grand Mosque','Heritage','https://picsum.photos/seed/passgo-grandmosque/1200/800',24.4128,54.4748,'09:00–22:00 (Fri pm only)',0,4.9,2,'82 marble domes and the world''s largest hand-knotted carpet.'),
('a_louvre','city_abudhabi','Louvre Abu Dhabi','Museum','https://picsum.photos/seed/passgo-louvre/1200/800',24.5339,54.3981,'10:00–18:30, closed Mon',17,4.7,3,'Jean Nouvel''s ''rain of light'' dome over a global collection.'),
('a_hagiasophia','city_istanbul','Hagia Sophia','Heritage','https://picsum.photos/seed/passgo-hagiasophia/1200/800',41.0086,28.9802,'09:00–19:00',27,4.8,1.5,'1,500 years of Byzantine and Ottoman history.'),
('a_bluemosque','city_istanbul','Blue Mosque','Temple','https://picsum.photos/seed/passgo-bluemosque/1200/800',41.0054,28.9768,'Outside prayer times',0,4.7,1,'Six minarets and a cascade of blue İznik tiles.'),
('a_grandbazaar','city_istanbul','Grand Bazaar','Market','https://picsum.photos/seed/passgo-grandbazaar/1200/800',41.0108,28.9682,'Mon–Sat 09:00–19:00',0,4.5,2,'4,000 shops of carpets, lamps, spices and gold.'),
('a_balloon','city_cappadocia','Sunrise Hot-Air Balloon','Adventure','https://picsum.photos/seed/passgo-balloon/1200/800',38.6431,34.8289,'Pre-dawn, weather permitting',200,4.9,3,'Float over fairy chimneys as the valleys catch first light.'),
('a_goreme','city_cappadocia','Göreme Open-Air Museum','Heritage','https://picsum.photos/seed/passgo-goreme/1200/800',38.6433,34.8447,'08:00–17:00',20,4.6,2,'Rock-cut churches with vivid Byzantine frescoes.'),
('a_caudan','city_portlouis','Caudan Waterfront','Shopping','https://picsum.photos/seed/passgo-caudan/1200/800',-20.1583,57.4986,'10:00–18:00',0,4.3,2,'Harbourside shops, casino and craft market.'),
('a_centralmarket','city_portlouis','Central Market','Market','https://picsum.photos/seed/passgo-centralmarket/1200/800',-20.1609,57.5012,'06:00–17:30',0,4.4,1.5,'Tropical fruit, spices and street snacks like dholl puri.'),
('a_blackriver','city_flicenflac','Black River Gorges NP','Nature','https://picsum.photos/seed/passgo-blackriver/1200/800',-20.4189,57.4467,'06:00–18:00',0,4.6,4,'Rainforest trails to waterfalls and endemic pink pigeons.'),
('a_snorkel','city_flicenflac','Flic en Flac Reef Snorkel','Beach','https://picsum.photos/seed/passgo-snorkel/1200/800',-20.2747,57.3661,'Daylight hours',25,4.5,3,'Calm lagoon swimming with clownfish and coral.')
on conflict (id) do nothing;

-- ── PREP GUIDES (flagship destinations) ──────────────────────────────────────
insert into prep_guides (dest_country, documents, vaccinations, currency, sim, safety, premium) values
('TZ',
  ARRAY['Passport valid 6+ months','Yellow fever certificate (if from an endemic country)','Return ticket & accommodation proof'],
  ARRAY['Yellow fever (conditional)','Hepatitis A','Typhoid','Malaria prophylaxis'],
  '{"tips":"USD widely accepted for tours and park fees; bring crisp post-2013 notes.","cards":"Cards work in hotels; ATMs dispense TZS.","cash":"Carry TZS for markets, dala-dalas and tips."}',
  '{"providers":["Vodacom","Airtel","Halotel"],"tips":"Buy a SIM at the airport with your passport; data is cheap."}',
  ARRAY['Dress modestly in Stone Town','Agree taxi fares in advance','Use reef-safe sunscreen'], true),
('ZA',
  ARRAY['Passport valid 6+ months','Return / onward ticket','Proof of accommodation'],
  ARRAY['Hepatitis A','Typhoid','Malaria prophylaxis (Kruger/lowveld)'],
  '{"tips":"The Rand is volatile — withdraw as you go.","cards":"Contactless is everywhere.","cash":"Keep cash for car-guard tips and markets."}',
  '{"providers":["Vodacom","MTN","Cell C"],"tips":"RICA registration needs your passport; buy at the airport."}',
  ARRAY['Avoid displaying valuables in cities','Don''t walk alone at night in CBDs','Use ride-hailing after dark'], true),
('TH',
  ARRAY['Passport valid 6+ months','Proof of onward travel','Accommodation booking'],
  ARRAY['Hepatitis A','Typhoid','Japanese encephalitis (rural/long stays)'],
  '{"tips":"Withdraw THB from ATMs or exchange at SuperRich.","cards":"Malls and hotels take cards; markets are cash-only.","cash":"Keep small notes for street food and tuk-tuks."}',
  '{"providers":["AIS","TrueMove H","dtac"],"tips":"Tourist SIMs with unlimited data at every airport."}',
  ARRAY['Cover shoulders & knees at temples','Use the meter or Grab','Beware jet-ski and gem scams'], true),
('AE',
  ARRAY['Passport valid 6+ months','Confirmed return ticket','Hotel booking'],
  ARRAY['Routine vaccines up to date'],
  '{"tips":"The Dirham is pegged to the USD (~3.67).","cards":"Cards accepted virtually everywhere.","cash":"Small cash for taxis and souks."}',
  '{"providers":["du","Etisalat (e&)"],"tips":"Tourist SIM at the airport; some VoIP calls are restricted."}',
  ARRAY['Respect conservative dress codes','No public displays of affection','Friday has limited hours at some sites'], true),
('TR',
  ARRAY['Passport valid 6+ months','e-Visa printout','Accommodation proof'],
  ARRAY['Routine vaccines up to date'],
  '{"tips":"Pay in Lira, not euros, for better value.","cards":"Widely accepted; carry cash for bazaars.","cash":"Small notes for tea, taxis and tips."}',
  '{"providers":["Turkcell","Vodafone TR","Türk Telekom"],"tips":"An eSIM is often cheaper for short trips."}',
  ARRAY['Haggle politely in the Grand Bazaar','Book balloon rides with licensed operators','Watch for friendly bar scams'], true),
('MU',
  ARRAY['Passport valid 6+ months','Return ticket','Accommodation proof'],
  ARRAY['Routine vaccines up to date'],
  '{"tips":"The Rupee is stable; resorts quote in EUR/USD too.","cards":"Accepted in resorts and supermarkets.","cash":"Cash for buses, markets and street food."}',
  '{"providers":["Emtel","my.t (Mauritius Telecom)"],"tips":"Cheap tourist data SIMs at the airport."}',
  ARRAY['Strong currents at some public beaches','Mosquito repellent in summer','Drive on the left if renting'], true)
on conflict (dest_country) do nothing;
